
name: "Continuous Integration"

on:
  pull_request:
    branches:
      - "*.x"
  push:
    branches:
      - "*.x"

jobs:
  phpunit:
    name: "PHPUnit"
    uses: "doctrine/.github/.github/workflows/continuous-integration.yml@1.2.1"
    with:
      php-versions: '["7.2", "7.3", "7.4", "8.0"]'

  phpunit-with-symfony-6:
    name: "PHPUnit with Symfony 6.0.x-dev"
    uses: "doctrine/.github/.github/workflows/continuous-integration-symfony-unstable.yml@1.4.0"
    with:
      symfony-version-constraint: "6.0.*"
